# Generated by Django 6.0.3 on 2026-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='api_job_created_f81cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatus',
            index=models.Index(fields=['job', 'timestamp'], name='api_jobstat_job_id_e97635_idx'),
        ),
    ]
