# Generated by Django 6.0.3 on 2026-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_api_job_created_f81cf5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
